language: python
python:
  - "3.6"
jobs:
    include:
      - stage: test
        script:
          - pip install pipenv
          - pipenv lock -r > requirements.txt
          - pip install -r /requirements.txt
          - make test
