version: "3.9"
services:
  telegram-svc:
    build:
      context: ./services/telegram_svc
      dockerfile: ./Dockerfile
    env_file: ./dev.env
    restart: "always"

  telebot-backend-svc:
    build:
      context: ./services/telebot_backend_svc
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: "always"
  