version: "3.9"
services:
  telegram-svc:
    image:
      anthonyfong/telegram-svc:latest
    build:
      context: ./services/telegram_svc
      dockerfile: ./Dockerfile
    env_file: ./dev.env
    restart: "always"

  telebot-backend-svc:
    image:
      anthonyfong/telebot-backend-svc:latest
    ports:
      - "8000:8000"
    restart: "always"
  