name: Build and test
on:
  push:
    branches:
      - main
      - releases/*

jobs:
  build:
    name: Build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anthonyfong/leetcode-tele-bot:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Update deployment file
        run: |
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} && sed -i 's/DOCKER_USERNAME/'${DOCKER_USERNAME}'/g' digital_ocean_deploy.sh
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} && sed -i 's/DOCKER_PASSWORD/'${DOCKER_PASSWORD}'/g' digital_ocean_deploy.sh
      - name: Update env file
        run: |
          TELEBOT_TOKEN=${{ secrets.TELEBOT_TOKEN }} && echo "\nTELEBOT_TOKEN=${TELEBOT_TOKEN}" >> prod.env
      - name: Delete previous Droplet 
        continue-on-error: true
        run: doctl compute droplet delete leetcode-tele-bot --force
      - name: Provision Droplet and deploy containers
        run: doctl compute droplet create leetcode-tele-bot --image docker-20-04 --size s-1vcpu-1gb --region sgp1 --user-data-file digital_ocean_deploy.sh  --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --wait --ssh-keys ${{ secrets.SSH_KEY }}
