name: Build and test
on:
  push:
    branches:
      - main
      - releases/*


jobs:
  build:
    name: Build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Authenticate with DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 180
      - name: Build and Push to DigitalOcean Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/anthonyfong97/leetcode-tele-bot:latest
            registry.digitalocean.com/anthonyfong97/leetcode-tele-bot:sha-${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Update deployment file
        run: sed -i 's/TOKEN_NAME/'${${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}}'/g' digital_ocean_deploy.sh
      - name: Delete previous Droplet 
        continue-on-error: true
        run: doctl compute droplet delete leetcode-tele-bot 
      - name: Provision Droplet and deploy containers
        run: doctl compute droplet create leetcode-tele-bot --image docker-20-04 --size s-1vcpu-1gb --region sgp1 --user-data-file digital_ocean_deploy.sh  --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --wait
