name: Build and test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Test commons lib
        run: |
          cd libs/common && poetry install && make test
      - name: Test telebot backend service
        run: |
          cd services/telebot_backend_svc && make
          poetry run pip install ./dist/**/*.whl
          poetry add -D pytest pytest-cov
          echo "reached here"
          make test
      - name: Test telegram service
        run: |
          cd services/telegram_svc && make 
          poetry run pip install ./dist/**/*.whl
          poetry add -D pytest pytest-cov
          make test
      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella 
          fail_ci_if_error: true 
          verbose: true
